README.md

Jane T - update name

---

__tests__/application.test.js

added test to check state versus (done with ML)

checking the state versus

---

backend/data/cards.json

now the keys match the id of the character.json

rewrote keys

---

__tests__/application.test.js
backend/data/app.json

The profile is now stored ID characters

Changed the contents of the profile

---

src/HeroSelection.js
src/css/App.css
src/css/HeroSelection.css

Eslint стабильно выдает 10 ошибок с пробелами, не знаю, как их исправить.
Добавлен компонент HeroDetails, который рендерится по нажатию на кнопку "Info", закрывающая кнопка и стили.

Frontend individual chacter component

---

__tests__/application.test.js
backend/data/app.json

Rewrote tests and app.json in such a way that only one character is available in the profile.

removed one character

---

__tests__/application.test.js
backend/data/characters.json

Добавила персонажам здоровье.
Почему-то появилась ошибка в App.js (3 строка)

add health to characters

---

__tests__/application.test.js
backend/gameEngine.js

sorry can not fix some lint errors

Hero and Cards are  assigned for inactive player

---

__tests__/application.test.js
backend/gameEngine.js

Ticket done
BACKEND: Прописать здоровье игроку при выборе персонажа

health assigned to players

---

src/css/HeroSelection.css

Поправила стили для кнопки Info

fix HeroBlockInactive's styles

---

src/css/HeroSelection.css

fix bug button info

---

README.md

add line breaks and code blocks for commands and keyboard shortcut to pretty view and readability

fix markdown for README.md

---

src/HeroSelection.js

Frontend heroselection inactive blocked

---

backend/data/cards.json
backend/data/characters.json
src/HeroSelection.js

тикет  BUG
https://trello.com/c/wVuf99BY

spelling has been corrected for cards and characters

---

backend/gameEngine.js

Trello card https://trello.com/c/QWQP0vwU (BACKEND: Переделать раздачу)
присвоены ключи каждой карте из колоды игрока от key  0 по key 14

trying to assign unique card id for hero decks

---

__tests__/application.test.js
backend/data/characters.json

Выявились еще неправильно написанные карты и Заглавные буквы в описании персонажа, которые валили тест. Исправлено.
https://trello.com/c/i0wEy4RN

fixed name spelling pro causing test fail

---

src/HeroSelection.js
src/css/App.css
src/css/HeroSelection.css
src/css/VersusScreen.css

Ticket from Trello https://trello.com/c/3y3sxpbm 
+ Also in hero pop up 1st letter in hero name is capitalized

font Sedan added to headers. 

---

main.js
src/ctxMenu.js
src/shortcuts
src/shortcuts.md

devops: context menu - minimal functionality 

---

__tests__/application.test.js
backend/gameEngine.js

Переписаны  тесты для обновленной  колоды с ключами
Трелло тикет
https://trello.com/c/9LlkeJAl

backend: deck with keys - tests

---

main.js
src/MainMenu.js

added: code to quit app by quit button in mainmenu
optional: simplified toggle function in mainmenu
https://trello.com/c/9pvmjTNZ

devops: mainmenu quit action

---

src/VersusScreen.js
src/css/MainMenu.css
src/css/StartScreen.css

- fixed position for mainmenu
- fixed position for startsscreen background
- added mainmenu to versusscreen
https://trello.com/c/8rmOCyJU

frontend: versusscreen - add mainmenu

---

src/HeroSelection.js
src/css/HeroSelection.css

bug: frontend - heroselection - popup not closed

---

__tests__/application.test.js
backend/gameEngine.js
backend/screenManager.js

переделан тикет https://trello.com/c/L15dvlDe
тест и код с обновленной колодой
done

Playeract case1 updated deck

---

backend/data/cards.json

Trello ticket https://trello.com/c/WvuCARgN
Добавлены очки в данные карт

cards with points

---

package.json

https://trello.com/c/7N9johIj/164-devops-%D1%80%D0%B0%D1%81%D1%81%D0%BC%D0%BE%D1%82%D1%80%D0%B5%D1%82%D1%8C-%D0%B2%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B1%D0%B8%D0%BB%D0%B4%D0%BE%D0%B2-%D0%B4%D0%BB%D1%8F-%D0%BB%D0%B8%D0%BD%D1%83%D0%BA%D1%81%D0%B0

package-linux script added

---

src/css/VersusScreen.css

https://trello.com/c/PMHVDlMd/169-bug-%D0%BD%D0%B0-%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B5-versus-%D1%80%D0%B0%D0%BC%D0%BA%D0%B0-%D0%BF%D0%BE%D0%B4-%D0%B8-%D0%BD%D0%B0%D0%B4-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%BE%D0%B9-%D0%BD%D0%B5-%D0%BD%D0%B0-%D1%81%D0%B2%D0%BE%D0%B5%D0%BC-%D0%BC%D0%B5%D1%81%D1%82%D0%B5

fixed hero border

---

src/ctxMenu.js

fixed bug with unmapped event
https://trello.com/c/EaZlP1Y6

devops: contextmenu - fix about

---

src/ctxMenu.js

added reload function to context menu
https://trello.com/c/ntj09nOQ

devops: contextmenu - reload

---

src/MainMenu.js
src/css/MainMenu.css

frontend:  mainmenu - close on focus out

---

src/GameScreen.js

changed health line to use real player health points
https://trello.com/c/m5PLoo7A

frontend: gamescreen - real health points

---

src/css/StartScreen.css

https://trello.com/c/5PYfDQRV картинка заставки теперь растягивается, но по-прежнему  съезжает анимация горящих окон

fix_bug_but_create_new

---

src/HeroSelection.js
src/css/HeroSelection.css
src/css/HeroSelection.module.css

Trello Ticket https://trello.com/c/l5fULGvy

CSS module added to HeroSelection

---

src/css/MainMenu.css

frontend: mainmenu - logo disappears

---

src/css/StartScreen.css

frontend: startscreen - background position

---

__tests__/application.test.js
backend/gameEngine.js

trello ticket https://trello.com/c/xZbezSoq

Case4 corr

---

src/MainMenu.js

frontend: mainmenu - logo element assignment

---

src/HeroSelection.js
src/MainMenu.js

trello ticket https://trello.com/c/Ww4hgxrw

Frontend bug props

---

.travis.yml

add build name

---

src/VersusScreen.js

fix required prop

---

src/HeroSelection.js
src/css/App.css
src/css/HeroSelection.css
src/css/HeroSelection.module.css

Trello ticket https://trello.com/c/boLgigCq

Character details fix

---

__tests__/application.test.js
backend/gameEngine.js

Backend 
trello ticket https://trello.com/c/3UXBagl2

Backend : to move active  card from Item to graveyard

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/C93x7hAF

type item fixed some comments added

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/JWgqUKSG
как всегда, gitHub чудит, ушло 2 файла, а отправляла только 1 - с тестами ( gameEngine захватился лишним)

Bug tests with mock random

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/4TNJlzxV
done with some tests failing once run all togerther
new ticket is opened for this bug

Living dead water

---

backend/gameEngine.js

Trello ticket https://trello.com/c/AOXfdxuK
функциональность изменена
но в мастере сейчас тесты валяться. нужны исправленные тесты из ветки mockTests
https://github.com/BITVA-Game/bitva-game/pull/132
тогда тесты подтверждают правильность
я не стала тесты включать сюда , если нужно напишите мне

magic number removed from assignCards function

---

__tests__/application.test.js

trello ticket https://trello.com/c/JWgqUKSG

tests rewrited with mock random returned

---

src/HeroSelection.js

Trello Ticket https://trello.com/c/4NVI0WzG

Refactoring hero selection step1

---

src/HeroSelection.js
src/ListOfHeroes.js
src/OneHero.js

move OneHero and ListOfHeroes to separate files

---

__tests__/application.test.js
backend/gameEngine.js

fix moveCounter and assign personal grave to each player

---

src/css/GameScreen.css

fix target class

---

src/GameScreen.js

show counter on enemy's grave

---

src/HeroSelection.js
src/css/HeroSelection.css
src/css/HeroSelection.module.css

https://trello.com/c/xOWpbjxV
https://trello.com/c/qXojEHzL

Hero select css fix

---

public/fonts/RuslanDisplay.css
public/fonts/Sedan-SC.css
src/App.js

fix fonts in builds

---

src/GameScreen.js
src/css/GameScreen.css

Cards game screen

---

src/css/HeroSelection.css

Change cards size and icons position

---

__tests__/application.test.js
backend/data/cards.json
backend/data/characters.json
backend/gameEngine.js
backend/sheets.js

attack damages only shield in item, other similar shields remain with their points

---

src/StartScreen.js
src/css/StartScreen.css

fix start screen animations

---

__tests__/application.test.js
backend/data/characters.json
backend/gameEngine.js
src/OneHero.js
src/Player.js

trello ticket - https://trello.com/c/haM5ryQK

water cards are now playable + tests and data are fixed

---

src/OneHero.js
src/css/HeroSelection.css

https://trello.com/c/DLAcnzXV
https://trello.com/c/4Qi2vbRu

Card section

---

backend/data/selectCharacter.json
src/ctxMenu.js

add select character option

---

src/ctxMenu.js

add return to start screen option

---

src/Player.js
src/css/GameScreen.css

fix card-in-item's opacity and position

---

src/GameScreen.js

show character's name in gameover message

---

src/HeroSelection.js
src/OneHero.js

Fix hero select

---

backend/gameEngine.js
src/GameScreen.js
src/css/GameScreen.css

Turn message

---

backend/data/characters.json
backend/data/morevnaStart.json

updated morevnaStart json with new cards and background and characters.json prettified
Trello Ticket https://trello.com/c/v6bWMT0A

updated morevnaStart json with new cards and background 

---

backend/data/selectCharacter.json

fix select character screen in debug menu

---

src/css/GameScreen.css

add target animation

---

src/HeroSelection.js
src/ListOfHeroes.js
src/OneHero.js

Fix HeroSelection to show sorted characters in correct order

Fix HeroSelection

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/FF8QDdov

heroSelected opponent id fixed + tests amended

---

src/Player.js
src/css/GameScreen.css

Trello Ticket https://trello.com/c/CQuGbs50

Animation Cards shuffle from graveyard to player's cards

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/3P1kFMvj

Magic mirror card

---

__tests__/application.test.js
src/HeroSelection.js

Random opponent

---

src/HeroSelection.js
src/ListOfHeroes.js
src/css/App.css
src/css/HeroSelection.css
src/css/MainMenu.css

Hover icons

---

src/VersusScreen.js

add img imports

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/13Gi8xIq

Magic tree card

---

__tests__/application.test.js
backend/gameEngine.js

trello ticket https://trello.com/c/QqOxSHOd

clairvoyance card tests and function have been added

---

__tests__/application.test.js
backend/gameEngine.js

Trello ticket https://trello.com/c/9k0Uzfst

Magic mirror corr

---

src/OneHero.js

Fix prop type and name

---

__tests__/application.test.js
backend/gameEngine.js
src/Player.js
src/rules.js

Trello ticket https://trello.com/c/1Y3UCJ41

Attackitem

---

__tests__/application.test.js
backend/gameEngine.js
package-lock.json
package.json
src/GameScreen.js

Trello ticket https://trello.com/c/Tk7BTMIZ

Heroes keys

---

__tests__/application.test.js
backend/data/cards.json
backend/data/characters.json
backend/sheets.js

Trello ticket https://trello.com/c/hHWtOPBc

Category name is added to cards dealt to players

---

src/OneHero.js
src/Player.js

show short category name on cards

---

__tests__/simpleactions.test.js
backend/gameEngine.js
src/Player.js
src/rules.js

trello ticket https://trello.com/c/aUi54jUf

Shield correct

---

src/rules.js

SkullLantern works now

---

__tests__/advancedactions.test.js
backend/gameEngine.js

malachite box card tests and function have been added

---

backend/data/cards.json
backend/data/characters.json
src/OneHero.js
src/Player.js

kikimora typo fix

---

__tests__/advancedactions.test.js
backend/gameEngine.js

Turning potion card

---

__tests__/advancedactions.test.js
backend/__mocks__/randomFunc.js
backend/data/cards.json
backend/data/characters.json
backend/gameEngine.js
src/Player.js
src/rules.js

https://trello.com/c/6AB6YB4C
Карта сделана на backend and frontend

Forest mushroom card

---

backend/data/characters.json
backend/gameEngine.js
src/OneHero.js
src/Player.js

https://trello.com/c/a4EY09wM
magicMirror card

add image, fix backend

---

__tests__/advancedactions.test.js
backend/data/cards.json
backend/data/characters.json
backend/gameEngine.js
src/OneHero.js
src/Player.js

Plate Mail card

---

src/Player.js

no target css for shield in item

---

__mocks__/stateMock.js
__tests__/terminal.test.js
gameEngine/heroSelect.js

terminal test for PLAY msg created

---

gameTerminal/application.js
src/ctxMenu.js

fix get back to start screen functionality

---

gameEngine/data/initialState.json
gameEngine/game.js
src/GameScreen.js
src/HeroSelection.js

Fix frontend

---

gameEngine/__data__/states.js
gameEngine/__tests__/engine.test.js
gameEngine/heroSelect.js
gameEngine/index.js

Trello ticket https://trello.com/c/2cGNeYu3

Engine test state2

---

src/Profile.js
src/css/Profile.css

Profile draft using hardcoded data to get rid of errors
First steo for https://trello.com/c/zmeoaTkY

Profile fix

---

gameEngine/__tests__/engine.turningpotion.test.js
gameEngine/data/initialState.json
gameEngine/game.js
gameTerminal/application.js
gameTerminal/data/hozyaikaStart.json
src/Card.js
src/GameScreen.js
src/Hand.js
src/Player.js
src/css/Cards.css
src/css/GameScreen.css
src/ctxMenu.js
src/rules.js

Turning Potion card 

---

src/GameScreen/index.js

change turn message fixed

---

constants.js
gameEngine/screen.js
gameTerminal/data/app.json
gameTerminal/screenManager.js
src/App.js
src/LoginScreen.js
src/css/LoginScreen.css

login screen

---

src/HeroSelection/OneHero.js
src/HeroSelection/index.js

no play button for unavailable heroes

---

src/App.js
src/GameScreen/index.js

and change turn fixed not t…o be shown once hero loses
https://trello.com/c/9cMnicbB

case over added to App.js showApplication 

---

src/GameScreen/Card.js
src/GameScreen/Hand.js
src/GameScreen/Player.js
src/GameScreen/index.js
src/css/Cards.css
src/css/GameScreen.css

turning potion animation 

---

gameEngine/__data__/cards.js
gameEngine/__tests__/engine.mushrooms.test.js

Forest Mushrooms Card Tests Refactoring

---

gameEngine/__tests__/engine.water.test.js
gameEngine/game.js

waterLiving card works now with magicTree combo

---

src/GameScreen/Card.js

background is now added for cards on GameScreen

---

main.js
src/ctxMenu.js

context menu on F4 button

---

main.js
src/ctxMenu.js

Keyboard inputs to reload (F5) and quit (F8) app.

add keyboard inputs to reload and quit app

---

src/App.js
src/LoginScreen/Login.js
src/LoginScreen/index.js
src/css/LoginScreen.css

Make chosen profile inaccessible

---

src/LoginScreen/DeleteLogin.js
src/LoginScreen/Login.js
src/LoginScreen/NewLogin.js
src/css/LoginScreen.css

Cancel button

---

src/LoginScreen/Login.js
src/PlayScreen.js
src/css/App.css
src/css/HeroSelection.css
src/css/LoginScreen.css
src/css/VersusScreen.css

profile vs profile screen layout

---

src/GameScreen/BoardContext.js
src/GameScreen/Card.js

Card drag bug

---

src/GameScreen/Hand.js
src/GameScreen/Player.js

propTypes fixed

---

src/GameScreen/Hand.js

in useEffect now check for cards keys not length

---

src/GameScreen/Item.js

item card can be chosen now onClick

---

.travis.yml
src/App.js
src/GameScreen/Card.js
src/GameScreen/Hand.js
src/GameScreen/Item.js

Fix card on click from item with  easy way

---

src/GameScreen/Hand.js
src/css/GameScreen.css

Cards animation fix

---

gameTerminal/data/cards.json
gameTerminal/sheets.js
src/GameScreen/Card.js
src/HeroSelection/OneHero.js
src/cardImages.js
src/css/Cards.css
src/css/GameScreen.css

Card right click

---

src/GameScreen/Card.js

fix scale value

---

gameTerminal/application.js
gameTerminal/systemManager.js
main.js
src/App.js
src/css/App.css

Fix bottom

---

src/GameScreen/Hand.js
src/soundController.js

Card anim sound

---

src/GameScreen/Hand.js
src/css/GameScreen.css

dragging now is fixed by remoiving preserve 3d from css class

---

src/MainMenu.js

frontend: fixed menu logo slide out

---

src/GameScreen/Hero.js

frontend: added information comments to the healthmeter calculations

---

src/css/Cards.css

fix chains

---

src/GameScreen/Hand.js
src/soundController.js

Fix cards sound

---

src/css/HeroSelection.css

deck icon on HeroSelect screen

---

src/HeroSelection/ListOfHeroes.js
src/css/HeroSelection.css

container size  has fixed size for Hero image on hero Selection screen

---

src/GameScreen/Hero.js
src/css/GameScreen.css

Make active player look more obvious active player with heartbeat (proposal)

heartbeat for active player (proposal)

---

src/LoginScreen/Login.js
src/LoginScreen/index.js
src/PlayScreen.js
src/VersusScreen.js
src/css/App.css
src/css/HeroSelection.css
src/css/LoginScreen.css
src/css/VersusScreen.css

DRY css for similar elements

---

src/GameScreen/AnimationBirds.js

correct time for birds animation is back now

---

src/GameScreen/Hand.js
src/GameScreen/Hero.js
src/GameScreen/Player.js
src/GameScreen/index.js

no sounds neither animation now after game OVER

---

src/LoginScreen/index.js
src/css/App.css
src/css/LoginScreen.css

fullscreen backgrounds and login screen animations

---

src/LoginScreen/Login.js

add footer on login screen to prevent inner content from moving up

---

src/GameScreen/Hero.js
src/soundController.js

single heart beat sound is played after change of active player

---

gameEngine/game.js
src/GameScreen/Player.js
src/css/GameScreen.css

Clairvoyancefix

---

src/GameScreen/index.js
src/HeroSelection/index.js
src/css/HeroSelection.css
src/rules.js

fix player name in messages

---

src/GameScreen/Hero.js
src/constants.js
src/soundController.js

fix vol of heartbit sound

---

src/HeroSelection/HeroSwiper.js
src/HeroSelection/ListOfHeroes.js
src/HeroSelection/OneHero.js
src/HeroSelection/index.js
src/css/App.css
src/css/HeroSelection.css
src/css/MainMenu.css

some fixes for large screens in HeroSelection

---

src/GameScreen/index.js
src/MainMenu.js
src/css/MainMenu.css

main menu on game screen

---

gameTerminal/data/accounts.json

now Delmer has both hidden pers

---

src/GameScreen/index.js
src/css/SnowAnimation.css

Snowfalkes  / fireflies  anim on GameScreen
